### ISSUE TITLE
Merkle proof verification

### ISSUE THREAD

**Issue by tomtau** [ChosunOne/merkle_bit#19]
**Is your feature request related to a problem? Please describe.**
This may be a question or a feature request -- I found this function https://github.com/ChosunOne/merkle_bit/blob/stable/src/merkle_bit.rs#L284 that generates a Merkle proof?
But I couldn't find the corresponding validation function -- i.e. given a tree root and a Merkle proof / path (I guess this list of treerefs or perhaps plus data), output if the proof is valid or not.

**Describe the solution you'd like**
If this functionality exists, then it'll be good to document in the example https://github.com/ChosunOne/merkle_bit/blob/stable/examples/main.rs how to use it.

If it doesn't exist, then it'll be good to add it. Ideally, it'll be a function separate from the tree storage (i.e. it'll only require to use the same Hasher, but no need to have access to the full storage), so that Merkle proofs from `merkle_bit` can be verified by thin / lite clients that only know the tree root.

(Also, I assume the proof generated from that function linked above are inclusion proofs. Exclusion proofs would also be desired, but I guess that would be a separate issue / feature request.)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ChosunOne** [comment]
Thanks for the suggestion!  You are indeed correct that the generate_treerefs function generates a merkle proof but isn't publicly exposed as it was recently refactored out from the inserting function.  

I'll make a public version for the purpose of verifying a given proof and will look into support for both inclusion and exclusion proofs.

**Comment by ChosunOne** [comment]
Closing this issue as inclusion proofs are now merged.
