### ISSUE TITLE
Use Digest trait instead of crate's own Hasher trait

### ISSUE THREAD

**Issue by spebern** [ChosunOne/merkle_bit#21]
Currently all hashes that are supported are directly inside the crate by implementing the `Hasher` trait.

There is the [`Digest`](https://docs.rs/digest/0.8.0/digest/trait.Digest.html) which lots of hashes in rusts crypto ecosystem already implement (https://github.com/RustCrypto/hashes). 

The main advantage would be that users are not restricted to the hashes supported inside this crate.

What do you think about replacing the crate's own `Hasher` trait by `Digest`?

**Comment by ChosunOne** [comment]
I like this idea in principle.  I'll have a look at what it would take to support `Digest` instead of the internal `Hasher` trait.

**Comment by ChosunOne** [comment]
I've left the `Hasher` trait in as it provides the interface I need for other crypto libraries, but I've implemented it for `Digest` meaning that you can now use any hasher provided it uses `Digest`.  Just activate the `use_digest` feature.  You can also now use the new features for hash types added in the latest nightly and beta.

**Comment by spebern** [comment]
Thanks!
