### ISSUE TITLE
Single get / insert + types

### ISSUE THREAD

**Issue by tomtau** [ChosunOne/merkle_bit#23]
# Development Process Improvement Proposal
## Observed Phenomenon
Currently there is:

```
    pub fn get<'a>(
        &self,
        root_hash: &[u8; KEY_LEN],
        keys: &mut [&'a [u8; KEY_LEN]],
    ) -> BinaryMerkleTreeResult<HashMap<&'a [u8; KEY_LEN], Option<ValueType>>> {
...
    pub fn insert(
        &mut self,
        previous_root: Option<&[u8; KEY_LEN]>,
        keys: &mut [&[u8; KEY_LEN]],
        values: &mut [&ValueType],
    ) -> BinaryMerkleTreeResult<[u8; KEY_LEN]> {
```
## Proposed Process Improvement
It would be good to also have:
```
    pub fn get_one(
        &self,
        root_hash: &[u8; KEY_LEN],
        key: &[u8; KEY_LEN],
    ) -> BinaryMerkleTreeResult<Option<ValueType>> {
...
    pub fn insert_one(
        &mut self,
        previous_root: Option<&[u8; KEY_LEN]>,
        key: &[u8; KEY_LEN],
        value: &ValueType,
    ) -> BinaryMerkleTreeResult<[u8; KEY_LEN]> {
```

And for the original methods, why not to have them take:
```
 keys: &[[u8; KEY_LEN]],
...
keys: &[[u8; KEY_LEN]],
values: &[ValueType],
```
instead ?

**Comment by ChosunOne** [comment]
The reason the get and insert methods currently require a mutable input is so that I can guarantee that the inputs are sorted.  It's possible to make a new array with sorted lists, but as that has a small performance penalty it wasn't clear to me if it was necessary yet.  

As for get and insert one, can you expand on why they are a good thing to have?

**Comment by tomtau** [comment]
ok, they could still be `mut`, but then why not
```
        keys: &mut [[u8; KEY_LEN]],
        values: &mut [ValueType]
```
?

If the client code has `Vec<[u8; KEY_LEN]>`, the current API which expects `&mut [&[u8; KEY_LEN]]` forces the client code to allocate / create a new vec of references.

For single key-value insert/lookup, it's a convenience (+ a reduction of overhead) that if one needs to insert/lookup one key/value, the client code doesn't need to wrap insertion arguments in vectors / size-1 arrays or unwrap lookup results from hashmaps

**Comment by ChosunOne** [comment]
Thanks for the clarification.  I'll benchmark and see what the results are.  The current API has evolved a lot, and way back when keys used to be variable sized vectors.  

There isn't any particular reason (aside from perhaps avoiding copying 32 bytes of memory all over the place), but if there is a major performance impact I'll move the references internally so you don't have to make them yourself.

**Comment by ChosunOne** [comment]
Latest nightly and beta have the changes you have suggested regarding the API changes.  I'll be preparing a release with the changes soon.

**Comment by tomtau** [comment]
>  The current API has evolved a lot, and way back when keys used to be variable sized vectors.

Just curious why did keys change to fixed sized arrays?

**Comment by ChosunOne** [comment]
This was done because benchmarks suggested 40% improvements in speed.  This is because fixed size things can go on the stack, and many internal structures need to own a copy of the key (especially if it comes out of the database).  

You can still modify the key length by changing the KEY_LEN constant but it seemed like a default of 32 bytes will cover virtually all use cases.

**Comment by tomtau** [comment]
what if there was a macro, so the client code could initialize structures with a different key length?
something like `merkle_bit!(key_size)`

**Comment by ChosunOne** [comment]
I can take a look at what it would take to make a macro for different key sizes, but I think it would be better to raise a separate issue from this one.

**Comment by tomtau** [comment]
ok, I'll close this one, as it's on nightly
https://github.com/ChosunOne/merkle_bit/commit/33aeda9f31d72bf4815c129915c75f01ff0da9db
