### ISSUE TITLE
API generic over key sizes 

### ISSUE THREAD

**Issue by tomtau** [ChosunOne/merkle_bit#25]
**Is your feature request related to a problem? Please describe.**
Currently, the key type is fixed to 32-byte arrays.

**Describe the solution you'd like**
Something more flexible without a significant performance impact (as mentioned here https://github.com/ChosunOne/merkle_bit/issues/23#issuecomment-497822918 the original API used `Vec<u8>`, but things were ~40% slower)

**Describe alternatives you've considered**
One option is to have a macro that would generate all the required structures with a chosen key length.

The other option would be to use a different array type, e.g.:

- `ArrayVec`: https://docs.rs/arrayvec/0.4.10/arrayvec/struct.ArrayVec.html
- `GenericArray`: https://crates.io/crates/generic-array
- ...

**Comment by ChosunOne** [comment]
I think the way that makes the most sense to go about this is to add an additional key type to the structure and bound it with necessary traits.  That way you can specify what kind of key you want to use, and the code will warn you if you try to use a type that isn't compatible with your hasher (as keys must be able to be created from hashes).  By default it will be a 32 byte array but you can change it based on the type arguments to the structure.

**Comment by ChosunOne** [comment]
Closing as this has now been released.
